// <auto-generated />
using System;
using EnglishSimulator.Desktop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnglishSimulator.Desktop.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260608105146_AddNameToDeck")]
    partial class AddNameToDeck
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("EnglishSimulator.Desktop.Data.Entities.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountSentensesPerLesson")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("EnglishSimulator.Desktop.Data.Entities.RepetitionInterval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeckId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stage")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.ToTable("RepetitionIntervals");
                });

            modelBuilder.Entity("EnglishSimulator.Desktop.Data.Entities.Sentence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeckId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnglishAudio")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RepeatDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RussianAudio")
                        .HasColumnType("TEXT");

                    b.Property<string>("RussianText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Stage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.ToTable("Sentences");
                });

            modelBuilder.Entity("EnglishSimulator.Desktop.Data.Entities.RepetitionInterval", b =>
                {
                    b.HasOne("EnglishSimulator.Desktop.Data.Entities.Deck", "Deck")
                        .WithMany("RepetitionIntervals")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("EnglishSimulator.Desktop.Data.Entities.Sentence", b =>
                {
                    b.HasOne("EnglishSimulator.Desktop.Data.Entities.Deck", "Deck")
                        .WithMany("Sentences")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("EnglishSimulator.Desktop.Data.Entities.Deck", b =>
                {
                    b.Navigation("RepetitionIntervals");

                    b.Navigation("Sentences");
                });
#pragma warning restore 612, 618
        }
    }
}
